[build]
builder = "nixpacks"
buildCommand = "npm run build:ssr"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 15

[env]
NODE_ENV = "production"
PORT = "3000"
HOST = "0.0.0.0" 